### ISSUE TITLE
Inclusion in Debian

### ISSUE THREAD

**Issue by HulaHoopWhonix** [exaexa/codecrypt#10]
Please submit your packages for inclusion in Debian repos. I would like to see your program in the next stable release so our project can take advantage of it.

Related: Do you host a stand-alone repo we can document installation from? Please consider adding 32-bit packages.

**Comment by exaexa** [comment]
I was actually just investigating that. There's once been codecrypt package already in debian but the official method is hard to remember and well kindof hard to maintain; is there some good method to e.g. create debian packages automatically just like tarballs with `make dist` ?

PS. patches/howtos welcome.

**Comment by mosra** [comment]
CMake does that (but ugly and non-conformant) :P

Otherwise, if you want just "ready to copypaste" solution, [have a look here](https://github.com/mosra/corrade/tree/master/package/debian), I tried to reduce all the bureaucracy bullshit to a minimum. Then the usage is just [calling `dpkg-buildpackage`](http://mosra.cz/blog/corrade-doc/building-corrade.html#building-corrade-packages-deb) and you have your `deb`s ready.

**Comment by exaexa** [comment]
Oh go on with cmake. :D

I've been just playing with git-buildpackage, it seems to survive my older dsc package just right. Will add to repo as soon as I get some grasp about the gazillion things it actually does. But I have 1.7.2 package working.

@HulaHoopWhonix any experience/examples with debian packaging from git? :]

btw the link for the older packages includes the .dsc: http://e-x-a.org/codecrypt/debian/

**Comment by exaexa** [comment]
Awright, this does the trick for me:

- go to https://github.com/exaexa/codecrypt-debian
- `git clone` that
- `gbp buildpackage` on master branch. You need git-buildpackage.

Can anyone of you please test if it also works for someone else than me? :]

**Comment by mosra** [comment]
Why a separate repo?

**Comment by exaexa** [comment]
Noob problems. It can probably be imported here as well, gbp tooling doesn't seem that useful after all.

**Comment by exaexa** [comment]
Well, there's now infrastructure for quickly generating correct form of packages, see 017ef07f4

**Comment by exaexa** [comment]
Debian Bug#814462

**Comment by HulaHoopWhonix** [comment]
@exaexa 


If there is an easy automated way for packaing i would like to know it. To make a package we usually use a pre-existing package as a template and then modify for the new one. You can see there the /debian sub folder. You could copy and paste it then change it for codecrypt:

https://github.com/Whonix/anon-mixmaster/tree/master/debian

Debian package build instructions are included in the project's readme.

https://github.com/Whonix/anon-mixmaster/blob/master/README.md

There is also the Debian mentors mailing list, which helps with
packaging questions.

https://lists.debian.org/debian-mentors/

You can reach out to the Debian Anonymity Tools or Debian Privacy Tools Teams for help:

https://tracker.debian.org/teams/anonymity-tools/

https://qa.debian.org/developer.php?email=pkg-privacy-maintainers%40lists.alioth.debian.org

**Comment by exaexa** [comment]
Already doing that, now waiting for processing in debian mentors. Don't you happen to know any willing debian sponsors? :]

About the automated way -- Can you please try `./autogen.sh ; ./configure; ./build-debian-package.sh 1.7.3 ` from master branch on your machine? It should easily produce all the package files in `debian-packages` dir. (requires devscripts pkg)

**Comment by exaexa** [comment]
RFS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814550

**Comment by HulaHoopWhonix** [comment]
Some Debian maintainers affiliated with privacy projects like Tor can be potential sponsors. Try to contact them all to increase your chances:

Peter Palfrader <weasel@debian.org>
Jacob Appelbaum <jacob@appelbaum.net>
Jérémy Bobbio <lunar@debian.org>
Ximin Luo <infinity0@debian.org>

When running the scripts above I get this error. The libtoolize dependency doesn't seem to be in Debian stable yet:

./autogen.sh: 33: ./autogen.sh: libtoolize: not found
bash: ./configure: No such file or directory
make: *** No rule to make target 'dist'.  Stop.

**Comment by mosra** [comment]
I still think that the package should be self-contained (and even better, re-entrant) to make it easy for users/packagers and automated building tools (e.g. -- I encounter `debian/` directory so I just run `debuild`; I encounter `PKGBUILD` file so I run `makepkg`; I encounter `package.rb` so I run `brew install package.rb` -- and nothing else, it should do everything including proper dependency checks for all related tools).

**Comment by exaexa** [comment]
@HulaHoopWhonix `apt-get install libtool pkg-config`

@mosra Well, is there an automated way for debuild to build the dist package so it can stop complaining about missing orig? Still I hope that anyone who sees ./build-debian-package.sh cannot possibly get confused. :]

**Comment by mosra** [comment]
> Still I hope that anyone who sees ./build-debian-package.sh cannot possibly get confused.

Buildbots won't see that ;)

Missing orig? What's that?

**Comment by exaexa** [comment]
.orig.tar.gz's are needed for quilt packages. And you can't pass native packages to debian if you don't have a proof that no debian patchwork will ever be needed. Which I obviously don't have.

**Comment by mosra** [comment]
Ahh, right, now I understand. Crazy overcomplicated rules :/ One would think that you as both a maintainer and a packager can provide "native" packages because all possible patches can be integrated right away in the upstream sources.

**Comment by exaexa** [comment]
upstream independence. :D

**Comment by exaexa** [comment]
After some struggle there's now separate repo for the debian herd: https://github.com/exaexa/codecrypt-debian

`gbp buildpackage` builds the package in the most maintainable way and everything. Going through the sponsoring process now.

**Comment by exaexa** [comment]
https://packages.debian.org/sid/codecrypt

<3

**Comment by HulaHoopWhonix** [comment]
@exaexa 
We have now included codecrypt by default in our anonymty OS distro Whonix which  will soon be released. I'm running codecrypt and loving it. I wanted to say  thanks again for your work on this great software.
