### ISSUE TITLE
Key Generating

### ISSUE THREAD

**Issue by Kushal08** [exaexa/codecrypt#12]
Hey, I am using th is code on my 64 bit ubuntu system. This command 
ccr -g sig --name "John  Deo"
It does not showing anything.I waited for two but keys are not generated. It is not ending.
Please help me in this issue.

**Comment by exaexa** [comment]
Can you install `strace` and post the output of

```
strace ccr -g sig --name 'xxx'
```

(be sure not to post anything secret, strace can reveal e.g. privkeys).

Also, is there completely _no_ output, or just some debugging messages? Generating FMTSeq keys takes some time, but there should be at least a message saying "gathering random bits" or so.

**Comment by Kushal08** [comment]
Sir,
     Thanks for replying. I ran the command that you said. The output
      is in the attached file.
      It stops again at the last line

**Comment by exaexa** [comment]
Nothing attached, please retry.

**Comment by Kushal08** [comment]
[output.txt](https://github.com/exaexa/codecrypt/files/292823/output.txt)

**Comment by exaexa** [comment]
Hm, seems okay. Please wait a bit more, it takes around 1 minute on my laptop. Also, be sure to compile with `./configure CXXFLAGS=-O3`. Because the cubehash function (that takes most of the keygen time) is in the compiled source, its speed is directly and very positively affected by the -O3 flag. If nothing happens _with_ -O3 after ~5 minutes, let me know.

**Comment by Kushal08** [comment]
![screenshot from 2016-06-01 20-08-56](https://cloud.githubusercontent.com/assets/11074001/15704073/7ded3c2e-2806-11e6-8443-be09fbd77ff4.png)

**Comment by exaexa** [comment]
Seems you've forgotten to actually rebuild the source. Sorry for not being verbose enough. :]

So:

```
./configure CXXFLAGS=-O3
make clean
make
```

should produce a lot faster code.

Please reopen if the problem persists.
