### ISSUE TITLE
import Frank's key and rename it

### ISSUE THREAD

**Issue by skyup259** [exaexa/codecrypt#13]
i am trying to import franks's key but showing error " ccr: could not open input file"
![screenshot from 2016-06-13 16-37-29](https://cloud.githubusercontent.com/assets/17674055/15997896/d88e8c2e-3156-11e6-9a5d-41584f0d7c56.png)

**Comment by exaexa** [comment]
It might not be quite obvious for people without any prior experience with GPG or no picture about how pubkey cryptography works, but "friend's pubkeys" are supposed to be sent to you by the friend ("Frank"). He produces the keys exactly same way as you do (exporting pubkeys using -p) and you simply exchange the files to be able to communicate.

I kindof hoped that, in the context of quick howto that shows you several quick tricks, this part will be clear thanks to the filename.

If the pubkeys really cannot be imported (e.g. you have a file from another machine and importing fails e.g. with a parse error), please reopen.

I'll add some comment to the howto.
