### ISSUE TITLE
how to send message and mdpc code

### ISSUE THREAD

**Issue by skyup259** [exaexa/codecrypt#14]
sir, i have done key generation by using given command:
         ccr -g sig --name "John Doe"    # your signature key
	ccr -g enc --name "John Doe"    # your encryption key 
but i didn't understand how to send message to anyone(i saw the example command but didn't understand)

also, i saw in pull request that mdpc code is given.can we implement mdpc code in codecrypt?

**Comment by exaexa** [comment]
MDPC is already implemented and default for the encryption in the last release.

Codecrypt works exactly like GnuPG with the messages: **it doesn't actually send the messages**, just takes your data and creates the encrypted/signed version of them that you can send to others via standard insecure means (mail/file transfer).

Just to summarize it up:

- first, this is a good read: https://en.wikipedia.org/wiki/Public-key_cryptography
- you make a file containing your supersecret message, call it `msg.txt`
- you run `ccr -k` to see what other people's pubkeys you have (if you have an encryption pubkey, starting with "E", you can send the corresponding person a secret message). Say you have a friend's pubkey called "Timmy"
- you run `ccr -e -r "Timmy" < msg.txt > encrypted_msg.txt.ccr`. The options mean "Encrypt for Recipient with name 'Timmy'".
- You send the `encrypted_msg.txt.ccr` to Timmy using some standard means, e.g. a plain unencrypted e-mail. You're pretty sure that enemy can't read that, unless they have pwned Timmy and own his private key.
- Timmy does `ccr -d < encrypted_msg.txt.ccr`. That finds his private key in his keyring and outputs exactly the content of original `msg.txt`.

For testing, you can also pretend you're Timmy to save bandwidth.

Also, for questions, please do not open issues -- ask on IRC or on some forums.

**Comment by skyup259** [comment]
thank you
