### ISSUE TITLE
Mac OSX install instructions

### ISSUE THREAD

**Issue by mapmeld** [exaexa/codecrypt#15]
Using Homebrew

- brew install libtool libcryptopp fftw
- replace libtoolize in autogen.sh with glibtoolize
- ```./autogen.sh```
- ```./configure --with-cryptopp=/usr/local/Cellar/cryptopp/5.6.3_1/lib/```
- ```make```
- ```make install```

**Comment by exaexa** [comment]
Good point, thanks. I don't own any OSX machine to test this stuff on -- would there be some suitable method to detect that the target is OSX in autogen to avoid users hand-hacking that?

Anyway, from portability side I don't see a way to make the `--with-cryptopp=.....` argument filled in automatically, library paths should be set-up correctly in advance for the build environment. On other systems, the path is filled in using pkg-config. Chances that something similar could work in OSX?
