### ISSUE TITLE
Annealmail Thunderbird Add-on

### ISSUE THREAD

**Issue by HulaHoopWhonix** [exaexa/codecrypt#17]
You may have seen it. There is a project that integrates codecrypt with Enigmail. I think that's awesome. You should talk with the dev and see if you can get this packaged for Debian too or maybe even upstreamed into Enigmail itself.

https://annealmail.github.io/
https://github.com/annealmail/annealmail

/cc @adrelanos

**Comment by exaexa** [comment]
I've seen it, it looks extremely useful and promising. I'll ping the author to see what are the actual possibilities of packaging are. If I understand it correctly, it's a complete fork of EnigMail; no idea what are the chances of merging the changes back upstream. Packaging for debian could be easy; EnigMail already has a packaging infra that can be reused.

**Comment by mapmeld** [comment]
feedback from the Enigmail email list in June was that post-quantum work is not something that they're interested in yet (noting lack of an official standard, comparing it to the Star Trek Enterprise) 
https://admin.hostpoint.ch/pipermail/enigmail-users_enigmail.net/2016-June/003946.html

I would be interested in seeing codecrypt as a package for Debian and Homebrew, but I haven't made something like that before

**Comment by exaexa** [comment]
codecrypt is already in debian stretch; would you mind creating a homebrew port? (I don't have a spare mac around).

IMHO best approach would be to create separate debian/homebrew packages also for annealMail; it would probably not pass debian's single-piece check if combined in one package.

Anyway, the discussion is a delightful read, thanks for the link :]

**Comment by mapmeld** [comment]
it's my first time working on a Homebrew formula. I'll have to look up how to install into ```/usr/local/bin``` and unfortunately I think it might be another change to the install script and not just a setting

```
 ./install-sh -c -d '/usr/local/share/man/man1'
  /bin/sh ./libtool   --mode=install /usr/bin/install -c ccr '/usr/local/bin'
 /usr/bin/install -c -m 644 man/ccr.1 '/usr/local/share/man/man1'
install: /usr/local/share/man/man1/ccr.1: Operation not permitted
make[1]: *** [install-man1] Error 71
make[1]: *** Waiting for unfinished jobs....
libtool: install: /usr/bin/install -c ccr /usr/local/bin/ccr
install: /usr/local/bin/ccr: Operation not permitted
make[1]: *** [install-binPROGRAMS] Error 71
make: *** [install-am] Error 2
```

**Comment by exaexa** [comment]
maybe set a different/correct --prefix? I assumed homebrew creates/chooses its own prefixes for each package, it should be forwarded to the build like here https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#grab-the-url

**Comment by HulaHoopWhonix** [comment]
Update:

Opened a Debian RFP:

https://bugs.debian.org/849321

**Comment by exaexa** [comment]
IMHO there are not many chances without finding some sponsor who'd package that for you. Also, is there a possibility to move this issue to AnnealMail's repo, as the topic is actually unrelated to codecrypt itself?

**Comment by HulaHoopWhonix** [comment]
Of course. I'll close this ticket then. I already have a ticket open there but there wasn't much feedback.

Do you know if your Debian sponsor is open to this? Can you give me his email so I can contact them?

**Comment by exaexa** [comment]
You may want to ask people on #debian-mentors on irc.oftc.net. There's a whole team dedicated to that matter, pkg-privacy, based here: https://alioth.debian.org/projects/pkg-privacy/
