### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [exaexa/codecrypt#21]
Dear Mirek,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by exaexa** [comment]
I don't have capacity to produce builds. More than that, I kindof believe that *especially for their own security* the users should be capable to compile the software themselves (and do it). I'd also be concerned about usage of current mainstream operating systems, but that's a completely different topic.

Compiling codecrypt for windos isn't even remotely complicated -- download the package from the website with the configure script, install cygwin, MSYS or any other free GNU environment for windows (I heard there's even an ubuntu prefix now) and proceed as with anything other (`./configure; make install`).

If you decide to build with crypto++ support (for SHA2 hashes and other more-standard-ish ciphers), download&compile&install their library first, they have excellent windos support. I also believe the same process can be done with fftw3 and gmp libraries (gmp will be very likely preinstalled in most GNU suites with a compiler).

Of course, if you reach any build errors or warnings, please report them; I'll happily fix the source to build cleanly on any platform.

Links:
http://mingw.org/wiki/msys
https://www.cygwin.com/
https://cryptopp.com/#download
http://www.fftw.org/install/windows.html
