### ISSUE TITLE
Entropy ?

### ISSUE THREAD

**Issue by deltaghost101** [exaexa/codecrypt#23]
Where does your program collect the required entropy to generate the key from ( /dev/random) ? Is there any possibility to include an external source of entropy to generate the keys ?

**Comment by exaexa** [comment]
Please do not mistake collecting entropy with seeding PRNG. Source of seed is `/dev/urandom` for nonces and similar stuff, and `/dev/random` for long-term keys, see `src/generator.cpp`. Please, always use a system with suitable random and urandom.

**Comment by exaexa** [comment]
Anyway, it is sometimes useful to play with other seed sources (although certainly not very wise for practical applications). I've added a patch that fixes ccr's behavior on seeding errors and allows the user to choose a different source (see manual).

**Comment by deltaghost101** [comment]
Thank you very much for adding the oppurtunity to seed from other sources , Excited :-)
