### ISSUE TITLE
A Question regarding HWRNG

### ISSUE THREAD

**Issue by deltaghost101** [exaexa/codecrypt#24]
Can we use a HWRNG that seeds directly to /dev/random like OneRNG with Codecrypt. Suppose if the user wants to add the support of an external TRNG with Codecrypt .

**Comment by exaexa** [comment]
If a hardware RNG already seeds the /dev/random, why not just use the default /dev/random?

Anyway, I don't have any hwrng device handy. Is there any reason why `export CCR_RANDOM_SEED=/dev/hwrng` wouldn't work? (use latest git btw, I added that yesterday.)

**Comment by deltaghost101** [comment]
Yeah export CCR_RANDOM_SEED=/dev/hwrng worked perfectly thanks for the information . Actually I don't trust Intel's RDRAND and I thought it might be useful to xor two streams together that is /dev/random and /dev/hwrng for paranoid security 😁

**Comment by exaexa** [comment]
It's not paranoia if they really are after you. Glad it works.
