### ISSUE TITLE
AES

### ISSUE THREAD

**Issue by LasersAreGreat** [exaexa/codecrypt#25]
I would like to respectfully request that support for AES256 in counter mode be added.

**Comment by exaexa** [comment]
+1 Pull requests accepted.

If you would go into implementing this, everything needed is to create an instance of streamcipher (see `chacha.h` and `chacha.cpp`) and assign it a name in `sc.cpp`. I gues crypto++ supports AES256-CTR so the whole thing shouldn't be complicated at all.

**Comment by exaexa** [comment]
Moving off github. Please reopen the issue at the new repository if needed.
