### ISSUE TITLE
Ubuntu Install Problem

### ISSUE THREAD

**Issue by heewon-chung** [exaexa/codecrypt#26]
Hi, 

I have already installed crypto++ (by $make, $make check, $make install). However, I have met a problem when ./configure.

Here is the error message.

./configure: line 16279: syntax error near unexpected token `CRYPTOPP,libcrypto++'
./configure: line 16279: `	PKG_CHECK_MODULES(CRYPTOPP,libcrypto++)'

Do you have any idea about it? My Ubuntu version is 16.04.3 LTS.

**Comment by exaexa** [comment]
`PKG_CHECK_MODULES` shouldn't even get to configure script. What did you use to create the configure script?

It also looks like I'm not checking for pkg-config but using it in configure.ac, I've added the check to current master `configure.ac`. Can you check if that helps (or at least provides a better error message?)

**Comment by exaexa** [comment]
Latest release adds explicit pkg-config check, so the error message should be much clearer. Install `pkg-config` to fix it.
