### ISSUE TITLE
Use LGPL v2.1 instead of v3 for better license compatibility

### ISSUE THREAD

**Issue by IBPX** [exaexa/codecrypt#27]
If you want to facilitate inclusion in other software, I think LGPL v2.1 is a much better choice, as LGPL v3 code can not be included in GPL v2 code (though it can be included in proprietary software), but LGPL v2.1 code can be included in both GPL v2 and v3 code.

See the [GNU license compatibility chart](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility).

If you want to switch, three people need to agree to re-licensing their contributions under the LGPL v2.1:

- [ ] @exaexa (the maintainer)
- [ ] @mapmeld
- [ ] @infinity0

**Comment by infinity0** [comment]
I don't think I contributed enough to be significant for copyright purposes, but in any case I agree to relicense to whatever everyone else thinks is necessary (as long as it's copyleft).

Personally I recommend sticking with LGPL3 unless there is a specific GPL2-only software that would like to link with codecrypt, where this becomes a concrete and not just hypothetical issue.

**Comment by IBPX** [comment]
FFTW3 is licensed as GPL v2 _or later_ so codecrypt including it is okay, but the resulting combination is licensed under the GPL v3 and _not_ the LGPL. Source of codecrypt is still LGPL, so someone could theoretically fork it and remove its dependency on FFTW3, and the resulting product would just be LGPL.

Crypto++ uses the Boost license which is GPL compatible according to the FSF, and from my (non-lawyer) reading of the license itself, seems like it should be LGPL compatible as well (without conveying the resulting combination as GPL), but I'm not sure. 

I don't know of any GPL v2-only software that wants to use codecrypt. This is just a hypothetical issue, but I think the more compatibility the better if there are no significant trade-offs that devs here care about. The main trade-off from what I've gathered is between more compatibility (which LGPL v2.1 offers) and disallowing closed hardware (which v3 does).

**Comment by exaexa** [comment]
about fftw3 -- we are linking against it, not including it, I guess that's the same?

**Comment by exaexa** [comment]
Timed out. Please reopen if you have a working project that will benefit from licence change.
