### ISSUE TITLE
It takes more than 10 minutes to generate keypair...

### ISSUE THREAD

**Issue by tearsofphoenix** [exaexa/codecrypt#32]
Why so slow on my mac air laptop & Ubuntu (14 core Xeon CPU, 32GB memory) ?

**Comment by exaexa** [comment]
FMTSeq keygen is a computationally intensive operation by design (and can't be generally sped up very much). The computation is single-threaded now so I guess you can add some parallelization to speed that up by using multiple cores.

Pull requests welcome.

**Comment by exaexa** [comment]
Moving off github. Please reopen the issue at the new repository if needed.
