### ISSUE TITLE
YAY: "Package 'libcrypto++', required by 'virtual:world', not found"

### ISSUE THREAD

**Issue by dlagg** [exaexa/codecrypt#36]
I'm trying to install codecrypt with yay (archlinux), the installation throws the following error:
`Package 'libcrypto++', required by 'virtual:world', not found`
I can't find this package to install it.

Output [here](https://gist.github.com/dlagg/cd3b6f720cbf4d0906f177e3f2a0abb1).

**Comment by exaexa** [comment]
Hello! This seems like archlinux packaging issue; likely the dependency broke or changed (or disappeared) and no one updated the codecrypt packaging metadata. Can you check:
- if libcrypto++ (sometimes called libcryptopp) is installed or at least declared in dependencies
- if it has a working pkg-config file
- if the .pc file points to valid libraries and headers?

**Comment by exaexa** [comment]
PS. you should be able to get a working codecrypt copy even without cryptopp library (with less algorithms supported though), by passing something like  `--without-cryptopp` to the configure script (see --help).

**Comment by exaexa** [comment]
@dlagg can you pls confirm/deny if the above config worked? so that we can either fix the thing for good or just close the issue :]

**Comment by exaexa** [comment]
I assume this has been fixed; if not please reopen. Also please note this might be a yay packaging problem (if libcrypto++ is renamed by distribution, distribution maintainers also need to feed the correct options that describe the change to configure scripts of depending packages).
