### ISSUE TITLE
Windows 8.1 Download

### ISSUE THREAD

**Issue by ajay340** [exaexa/codecrypt#7]
Hello,
I want to try codecrypt but I was wondering when will there be a download for Windows?

**Comment by exaexa** [comment]
I am sorry about that, but I do not have capacity to provide binary packages for any operating system. I shall close this until I have time. If someone volunteers to make packages (it isn't anything complicated, just a bit time-consuming), please reopen.

Anyway, for the solution: You can easily install MSYS ( http://www.mingw.org/wiki/msys or something similar ) and continue with installation exactly as in the readme, or cross-compile from unix using the xmingw32 (or how is it called now). Be sure to disable the Crypto++ dependency as I'm not sure whether that library has ever been built for Windows.

If you come across any issues, please report them - I remember that I only tried the cross-compilation method, and didn't test the binary on real Windows.

I should provide a bit of precaution though - rumors are that using newer versions of Windows for anything security-related might not be secure at all.

**Comment by mike805** [comment]
I just finished porting codecrypt to win32.
https://github.com/mike805/codecrypt-win32
Please report any bugs_
