### ISSUE TITLE
crypto++ header location

### ISSUE THREAD

**Issue by ghost91-** [exaexa/codecrypt#8]
The crypto++ headers are placed in the folder "<prefix>/include/cryptopp" (at least the make script of crypto++ and arch linux place it at that directory). The codecrypt currently assumes it to be in the folder "<prefix>/include/crypto++".

**Comment by exaexa** [comment]
I will try to use pkgconfig for discovering the location of the headers. Please workaround with explicit `./configure CPPFLAGS=...` in the meantime.

**Comment by exaexa** [comment]
The thing seems to be put into `include/crypto++` folder in debian and some other distros. What output do you get from  `pkg-config libcrypto++ --cflags` ?

**Comment by ghost91-** [comment]
```pkg-config libcrypto++ --cflags``` returns nothing on my machine.

**Comment by exaexa** [comment]
I was hoping it would return the correct crypto++ include path. Can you think of some other good method to portably detect the path to headers? (I'm not sure if "try this else that" approach would fit in autotools logic)

**Comment by ghost91-** [comment]
I just had a look at [amule](http://www.amule.org/), which also uses crypto++ in order to see, what they do to solve this issue. They simply check for both directories: https://github.com/amule-project/amule/blob/master/m4/cryptopp.m4

**Comment by exaexa** [comment]
Just realized that debian adds compatibility symlink cryptopp->crypto++. Asking arch guys to do the same would be nice.

Nevermind, I added a test that should handle both cases accordingly, please try the latest git dbce46b48a

I hope there are no more possibilities where the headers could go.

**Comment by ghost91-** [comment]
Thanks it works fine now. I guess this can be closed.

**Comment by exaexa** [comment]
Cool, thanks for report.
