### ISSUE TITLE
linkage to the pthread library

### ISSUE THREAD

**Issue by ghost91-** [exaexa/codecrypt#9]
When trying to compile codecrypt, i recieved the following errors:
```
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libcryptopp.so: undefined reference to `pthread_key_create'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libcryptopp.so: undefined reference to `pthread_getspecific'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libcryptopp.so: undefined reference to `pthread_key_delete'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libcryptopp.so: undefined reference to `pthread_setspecific'
```
Simply adding "-lpthread" to the linker flags in "autogen.sh" solves this.

**Comment by exaexa** [comment]
What environment are you using for compiling? Codecrypt itself doesn't use pthreads, this dependency should get pulled in by -lcryptopp. 

Check out if `ldd /usr/lib/libcryptopp.so` outputs pthread. If not, putting -lpthread manually to LIBS for your `./configure` is a good workaround.

**Comment by exaexa** [comment]
Relating to the other issue, what output do you get from `pkg-config libcrypto++ --libs` ?

**Comment by ghost91-** [comment]
I'm compiling on Arch Linux x86_64. ```ldd /usr/lib/libcryptopp.so``` did not output pthread. I compiled the most recent version of crypto++ and ldd did return pthread when in this case, so i suppose this is either a bug of crypto++ or the arch package.

```pkg-config libcrypto++ --libs``` returns -lcryptopp

**Comment by exaexa** [comment]
Anyway, from debian source package:

```
~/libcrypto++-5.6.1/debian $ grep pthread changelog
  * Link with pthread to avoid warning from dpkg-shlibdeps.
  * Use LDFLAGS=-pthread to fix linking errors.
```

Debian is explicitly fixing this for the package to avoid dependency breakage. Asking either Crypto++ or Arch packaging folks about the reason for this behavior will probably be the best option to solve this.

**Comment by exaexa** [comment]
Shall be resolved by upstream, closing.

If there's some quick&portable fix/workaround for detection whether cryptopp needs -pthread added, please submit a patch.
